sudo: false

language: node_js

services:
  - docker

node_js:
  - 4
  - 5
  - 6
  - 7

env:
  global:
    - AWS_ACCESS_KEY_ID=AKID
    - AWS_SECRET_ACCESS_KEY=SECRET
    - AWS_REGION=us-east-1
before_script:
  - docker-compose -f ./dev/docker-compose.yml up -d dynamodb
  - sleep 2
script: npm run ci
after_success: npm run coveralls
